name: Scraper Diario de Eventos

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar mi código
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # Acelera las ejecuciones futuras

      - name: Instalar librerías
        run: pip install -r requirements.txt

      # ESTE PASO ES CLAVE PARA EL DEBUG
      - name: Verificar Integridad del Modelo
        run: |
          echo "--- Información del archivo ---"
          ls -lh modelo_clasificador_eventos.pkl || echo "Archivo no encontrado"
          file modelo_clasificador_eventos.pkl || echo "No se pudo determinar el tipo"

      - name: Ejecutar el Scraper
        run: python scrp-tkt-evb-ede.py
        env:
          GCP_SERVICE_ACCOUNT_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
          EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
