name: Scraper Diario de Eventos
on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 
permissions:
  contents: read
jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar mi código
        uses: actions/checkout@v4

      - name: Cache memoria scrapers
        uses: actions/cache@v4
        with:
          path: memoria/
          key: memoria-scrapers-${{ runner.os }}
          restore-keys: |
            memoria-scrapers-

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar librerías
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar el Scraper
        run: python scrp-tkt-evb-ede.py
        env:
          GCP_SERVICE_ACCOUNT_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
          EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
