name: Scraper Diario de Eventos

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

env:
  # Esto elimina el warning de Node.js 20
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar mi código
        uses: actions/checkout@v4 # Ya usas v4, está bien.

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Subimos a 3.12 para eliminar el warning de Google

      - name: Instalar librerías
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar el Scraper
        run: python scrp-tkt-evb-ede.py
        env:
          GCP_SERVICE_ACCOUNT_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
          EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
